### ISSUE TITLE
Replication time

### ISSUE THREAD

**Issue by xinyu-daidai** [tlamadon/blm-replicate#6]
Dear Professor Lamadon, 

I try to replicate this project on a server with 96 cores and 384g RAM but it seems that the function `server.static.mixture.estimate.boostrap()` will still take me roughly 4-5 days to get the results. Do you think it is normal?

I am not sure whether there will be even longer functions after this super long one. (like `server.dynamic.mixture.d2003.boostrap()` may also be time-consuming?) Could you please tell me that usually how long it will take to replicate the whole project?

Thanks a lot!!

Best,
Xinyu

**Comment by tlamadon** [comment]
Hi, it does sound a bit long, but not crazy. Each replication goes through several starting values in the EM, so each is quite long. From memory it took us one to two days, but we had less cores. This is why it sounds a bit slow to me. The dynamic shouldn't take longer, it is a very similar procedure. 

I do wonder if you were able to use the 96 cores effectively. Also how large is your data?

**Comment by xinyu-daidai** [comment]
Thanks for the reply! I think what I did is just run it on Docker by `source("inst/main.R")` so all the setting is by default. Here is a snapshot of the program. 
<img width="959" alt="508bb7f9a52a35b13c188d5b064c596" src="https://user-images.githubusercontent.com/36264545/141383166-51b5821f-9f74-4df4-a8e4-d55c8065b4f1.png">
I roughly spent 13 hours to finish 60/200 loops for the function `server.static.mixture.estimate.boostrap()` and then stopped the server. Do you think it is acceptable to reduce the iteration times (still maintain a relatively robust result)? Cause currently I only need to generate a rough result in a short time.

**Comment by tlamadon** [comment]
Can you check your cpu load on your computer? My question is whether you let your docker use as many cores at it wants. Not sure what platform you are on.

**Comment by xinyu-daidai** [comment]
I don't know... Actually, it was my friend @0xf3cd who helped me deploy it on AWS and now we have stopped the server. But I eventually got the results by reducing the bootstrap iterations, so my problem is temporarily solved. Thanks a lot for the help! 😃

**Comment by 0xf3cd** [comment]
I helped @dxy99999 with deploying the project on an AWS EC2 instance. The CPU utilization fluctuated between around 60% and 100%, and it could reach 100% and last for minutes. So I believe all the 96 vCPUs were in use.
However, the usage of the memory was not monitored. Does `server.static.mixture.estimate.boostrap()` require high amount of memory (in which case docker may limit the memory usage by default)?

**Comment by tlamadon** [comment]
Hi guys, thanks for running this stuff. I don't think the memory requirement would be an issue. I think it is possible that running the whole bootstrap would take that much time. They way the parallelization is built, I can only use 50 parallel processes (number of starting values in the EM). I believe 1vCPU is like half an actual cpu, so maybe it adds up. This is simply a very very long process.  

One could make the bootstrap replications in parallel and use even more cores. From memory, the current version of the code doesn't do that. The bootstrap is only to get standard errors. If you focus on estimates you can skip that step.

I hope this help. Exciting that you were able to run this on AWS.

**Comment by xinyu-daidai** [comment]
Yeah, we finally used a relatively small iteration number during the bootstrap. Parallelizing the bootstrap process is a great idea. I believe this will help when I need to estimate a finite mixture model next time. 😃 Thanks a lot!
